'use strict';
const assert = require('node:assert/strict');
const api = require('../shared/anime-catalog.js');
const source = require('../shared/anime-metadata.js');
const builtins = require('../app/catalog-data.js').filter(x=>x.type==='anime');
const catalog = api.items(builtins,'desktop');
const movies = catalog.filter(x=>x.type==='movie');
assert.equal(source.rows.length,4132);
assert.equal(movies.length,1001);
assert(movies.every(x=>x.type==='movie'&&x.id==='vidsrc-movie-'+x.tmdbId));
assert(source.rows.every(x=>x.adult===false&&(x.type==='tv'?x.video===null&&x.classification==='Q63952888':x.video===false&&x.classification==='Q20650540')));
assert.equal(catalog.filter(x=>x.type==='anime').length,3131);
for(const builtin of builtins) assert.equal(catalog.find(x=>x.tmdbId===builtin.tmdbId&&x.type==='anime').id,builtin.id);
for(const id of ['13916','30991','209867','96451']) assert(catalog.some(x=>x.tmdbId===id&&x.type==='anime'));
for(const id of ['129','128','8392','573730']) assert(movies.some(x=>x.tmdbId===id));
const spirited=movies.find(x=>x.tmdbId==='129');
assert.equal(spirited.name,'Spirited Away');assert.equal(spirited.year,'');assert.equal(spirited.rating,'');
assert.equal(spirited.artworkUrl,'');assert(!spirited.providerListed);
assert(api.matchesQuery(spirited,'千と千尋'));
assert(api.matchesQuery({name:'Pokémon: The First Movie'},'Pokemon'));
const reused = api.items([Object.assign({},spirited,{id:'existing-film'})],'desktop');
assert.equal(reused.find(x=>x.tmdbId==='129').id,'existing-film');
assert.equal(JSON.parse(JSON.stringify(spirited)).id,spirited.id);
assert.equal(api.items([], 'tv').find(x=>x.tmdbId==='129').id,'movie-129');
const first=api.page(builtins.concat(catalog),'library',1,'');
const next=api.page(builtins.concat(catalog),'library',2,'');
assert.equal(first.total,4132);assert.equal(first.items.length,40);assert(first.canLoadMore);
assert(!next.items.some(x=>first.items.some(y=>api.identity(x)===api.identity(y))));
assert.equal(api.page(builtins.concat(movies),'movies',1,'').total,1001);
assert.equal(api.page(builtins.concat(movies),'movies',1,'Spirited Away').items[0].tmdbId,'129');
assert.equal(api.page([spirited,spirited,{id:'series129',tmdbId:'129',type:'anime',name:'Same root TV'}],'library',1,'').total,2);
assert.equal(api.page(movies,'movies',999,'').items.length,0);
assert.deepEqual(api.filters().map(x=>x.label),['Library','Movies']);
console.log('Offline anime library, identity, fields, paging and search fixtures passed.');
