(function exposeCatalog(root, factory) {
  var catalog = factory();
  if (typeof module === 'object' && module.exports) module.exports = catalog;
  if (root) root.HarborCatalogData = catalog;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createCatalog() {
  'use strict';

  return [
  // ==================== WATCH (MOVIES, SHOWS, ANIME, LIVE TV) ====================
  {
    id: 'w-1',
    tmdbId: '693134',
    name: 'Dune: Part Two',
    category: 'Watch',
    type: 'movie',
    year: 2024,
    rating: '8.6',
    sections: ['Movie', 'Sci-Fi'],
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    artworkUrl: 'https://image.tmdb.org/t/p/w780/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-2',
    tmdbId: '533535',
    name: 'Deadpool & Wolverine',
    category: 'Watch',
    type: 'movie',
    year: 2024,
    rating: '8.5',
    sections: ['Movie', 'Action'],
    overview: 'A listless Wade Wilson teams up with a reluctant Wolverine to face an existential threat.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-3',
    tmdbId: '872585',
    name: 'Oppenheimer',
    category: 'Watch',
    type: 'movie',
    year: 2023,
    rating: '8.9',
    sections: ['Movie', 'Biography'],
    overview: 'The story of J. Robert Oppenheimer role in the development of the atomic bomb.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-4',
    tmdbId: '569094',
    name: 'Spider-Man: Across the Spider-Verse',
    category: 'Watch',
    type: 'movie',
    year: 2023,
    rating: '9.0',
    sections: ['Movie', 'Animation'],
    overview: 'Miles Morales catapults across the Multiverse to encounter a team of Spider-People.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-5',
    tmdbId: '157336',
    name: 'Interstellar',
    category: 'Watch',
    type: 'movie',
    year: 2014,
    rating: '8.7',
    sections: ['Movie', 'Sci-Fi'],
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.',
    artworkUrl: 'https://image.tmdb.org/t/p/w780/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-6',
    tmdbId: '155',
    name: 'The Dark Knight',
    category: 'Watch',
    type: 'movie',
    year: 2008,
    rating: '9.0',
    sections: ['Movie', 'Action'],
    overview: 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-7',
    tmdbId: '27205',
    name: 'Inception',
    category: 'Watch',
    type: 'movie',
    year: 2010,
    rating: '8.8',
    sections: ['Movie', 'Sci-Fi'],
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-8',
    tmdbId: '603',
    name: 'The Matrix',
    category: 'Watch',
    type: 'movie',
    year: 1999,
    rating: '8.7',
    sections: ['Movie', 'Action'],
    overview: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-9',
    tmdbId: '550',
    name: 'Fight Club',
    category: 'Watch',
    type: 'movie',
    year: 1999,
    rating: '8.8',
    sections: ['Movie', 'Drama'],
    overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-10',
    tmdbId: '680',
    name: 'Pulp Fiction',
    category: 'Watch',
    type: 'movie',
    year: 1994,
    rating: '8.9',
    sections: ['Movie', 'Crime'],
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-11',
    tmdbId: '1396',
    name: 'Breaking Bad',
    category: 'Watch',
    type: 'tv',
    year: 2008,
    rating: '9.5',
    sections: ['TV Show', 'Crime'],
    overview: 'A chemistry teacher diagnosed with lung cancer turns to manufacturing and selling methamphetamine.',
    seasons: [
      { season_number: 1, name: 'Season 1', episode_count: 7 },
      { season_number: 2, name: 'Season 2', episode_count: 13 },
      { season_number: 3, name: 'Season 3', episode_count: 13 },
      { season_number: 4, name: 'Season 4', episode_count: 13 },
      { season_number: 5, name: 'Season 5', episode_count: 16 }
    ],
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-12',
    tmdbId: '66732',
    name: 'Stranger Things',
    category: 'Watch',
    type: 'tv',
    year: 2016,
    rating: '8.6',
    sections: ['TV Show', 'Sci-Fi'],
    overview: 'A small town uncovers a mystery involving secret experiments and terrifying supernatural forces.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-13',
    tmdbId: '100088',
    name: 'The Last of Us',
    category: 'Watch',
    type: 'tv',
    year: 2023,
    rating: '8.9',
    sections: ['TV Show', 'Drama'],
    overview: 'Joel and Ellie traverse a post-pandemic America facing ruthless killers and monsters.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-14',
    tmdbId: '1399',
    name: 'Game of Thrones',
    category: 'Watch',
    type: 'tv',
    year: 2011,
    rating: '8.4',
    sections: ['TV Show', 'Fantasy'],
    overview: 'Seven noble families fight for control of the mythical land of Westeros.',
    artworkUrl: 'https://image.tmdb.org/t/p/w780/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    seasons: [
      { season_number: 1, name: 'Season 1', episode_count: 10 },
      { season_number: 2, name: 'Season 2', episode_count: 10 },
      { season_number: 3, name: 'Season 3', episode_count: 10 },
      { season_number: 4, name: 'Season 4', episode_count: 10 },
      { season_number: 5, name: 'Season 5', episode_count: 10 },
      { season_number: 6, name: 'Season 6', episode_count: 10 },
      { season_number: 7, name: 'Season 7', episode_count: 7 },
      { season_number: 8, name: 'Season 8', episode_count: 6 }
    ],
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-15',
    tmdbId: '94997',
    name: 'House of the Dragon',
    category: 'Watch',
    type: 'tv',
    year: 2022,
    rating: '8.4',
    sections: ['TV Show', 'Fantasy'],
    overview: 'The Targaryen dynasty at the absolute apex of its power, with more than 15 dragons under their yoke.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-16',
    tmdbId: '126308',
    name: 'Shogun',
    category: 'Watch',
    type: 'tv',
    year: 2024,
    rating: '8.8',
    sections: ['TV Show', 'History'],
    overview: 'Lord Yoshii Toranaga discovers secrets that could tip the scales of power in feudal Japan.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-17',
    tmdbId: '93405',
    name: 'Squid Game',
    category: 'Watch',
    type: 'tv',
    year: 2021,
    rating: '8.0',
    sections: ['TV Show', 'Thriller'],
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children games.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-18',
    tmdbId: '76479',
    name: 'The Boys',
    category: 'Watch',
    type: 'tv',
    year: 2019,
    rating: '8.5',
    sections: ['TV Show', 'Action'],
    overview: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-19',
    tmdbId: '85937',
    name: 'Demon Slayer: Kimetsu no Yaiba',
    category: 'Watch',
    type: 'anime',
    year: 2019,
    rating: '8.7',
    sections: ['Anime', 'Action'],
    overview: 'Tanjiro Kamado sets out to become a demon slayer to avenge his family and cure his sister.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-20',
    tmdbId: '1429',
    name: 'Attack on Titan',
    category: 'Watch',
    type: 'anime',
    year: 2013,
    rating: '9.1',
    sections: ['Anime', 'Dark Fantasy'],
    overview: 'Young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.',
    artworkUrl: 'https://image.tmdb.org/t/p/w780/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
    seasons: [
      { season_number: 1, name: 'Season 1', episode_count: 25 },
      { season_number: 2, name: 'Season 2', episode_count: 12 },
      { season_number: 3, name: 'Season 3', episode_count: 22 },
      { season_number: 4, name: 'The Final Season', episode_count: 28 }
    ],
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-21',
    tmdbId: '94605',
    name: 'Jujutsu Kaisen',
    category: 'Watch',
    type: 'anime',
    year: 2020,
    rating: '8.8',
    sections: ['Anime', 'Supernatural'],
    overview: 'Yuji Itadori enters Tokyo Prefectural Jujutsu High School after swallowing a cursed talisman.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-22',
    tmdbId: '209867',
    name: 'Solo Leveling',
    category: 'Watch',
    type: 'anime',
    year: 2024,
    rating: '8.9',
    sections: ['Anime', 'Action'],
    overview: 'Sung Jinwoo finds himself in a mysterious quest enabling him to level up.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-23',
    tmdbId: '37854',
    name: 'One Piece (Anime Series)',
    category: 'Watch',
    type: 'anime',
    year: 1999,
    rating: '8.9',
    sections: ['Anime', 'Adventure'],
    overview: 'Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-24',
    tmdbId: '46260',
    name: 'Naruto: Shippuden',
    category: 'Watch',
    type: 'anime',
    year: 2007,
    rating: '8.6',
    sections: ['Anime', 'Ninja'],
    overview: 'Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval.',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-bleach',
    tmdbId: '30984',
    name: 'Bleach',
    category: 'Watch',
    type: 'anime',
    year: 2004,
    rating: '8.4',
    sections: ['Anime', 'Action'],
    overview: 'Ichigo Kurosaki becomes a Soul Reaper and protects the living and the dead from Hollows.',
    artworkUrl: 'https://image.tmdb.org/t/p/w780/5iVUUnE2tgBPypACYNobCKHagfV.jpg',
    seasons: [
      { season_number: 1, name: 'Bleach', episode_count: 366 },
      { season_number: 2, name: 'Thousand-Year Blood War', episode_count: 50 }
    ],
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'EMBED PROVIDER', badge: 'badge-embed' }]
  },
  {
    id: 'w-25',
    tmdbId: 'live-sports',
    name: 'World Sports HD Live Feed',
    category: 'Watch',
    type: 'live',
    year: 2026,
    rating: '9.2',
    sections: ['Live TV', 'Sports'],
    overview: 'Continuous live sports stream relay with low latency 60fps feed.',
    directStream: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    sources: [{ name: 'STREAM RELAY', badge: 'badge-relay' }]
  },
  {
    id: 'w-26',
    tmdbId: 'live-news',
    name: 'Global 24/7 News Network',
    category: 'Watch',
    type: 'live',
    year: 2026,
    rating: '8.8',
    sections: ['Live TV', 'News'],
    overview: 'International breaking news and live broadcast stream relay.',
    directStream: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sources: [{ name: 'STREAM RELAY', badge: 'badge-relay' }]
  },

  // ==================== READ (MANGA, NOVELS, BOOKS, COMICS) ====================
  {
    id: 'r-1',
    name: 'Berserk (Deluxe Edition Manga Vol. 1-14)',
    category: 'Read',
    type: 'manga',
    year: 2023,
    rating: '9.8',
    sections: ['Manga', 'Dark Fantasy'],
    overview: 'The legendary dark fantasy manga following Guts the Black Swordsman seeking revenge on Griffith.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-2',
    name: 'One Piece Manga (Complete Volumes 1-108)',
    category: 'Read',
    type: 'manga',
    year: 2024,
    rating: '9.6',
    sections: ['Manga', 'Adventure'],
    overview: 'Monkey D. Luffy explores the Grand Line in search of the legendary One Piece treasure.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-3',
    name: 'Chainsaw Man (Complete Manga Part 1 & 2)',
    category: 'Read',
    type: 'manga',
    year: 2024,
    rating: '9.3',
    sections: ['Manga', 'Action'],
    overview: 'Denji becomes Chainsaw Man by making a contract with the chainsaw devil Pochita.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-4',
    name: 'Vagabond (Definitive Edition by Takehiko Inoue)',
    category: 'Read',
    type: 'manga',
    year: 2023,
    rating: '9.7',
    sections: ['Manga', 'Samurai'],
    overview: 'The fictionalized account of the life of legendary Japanese swordsman Miyamoto Musashi.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-5',
    name: 'Vinland Saga (Complete Manga Box Sets)',
    category: 'Read',
    type: 'manga',
    year: 2024,
    rating: '9.5',
    sections: ['Manga', 'Historical'],
    overview: 'Thorfinn pursues a journey with his father killer in order to take revenge and end that life.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-6',
    name: 'Dune Chronicles by Frank Herbert (Books 1-6 EPUB/PDF)',
    category: 'Read',
    type: 'book',
    year: 2023,
    rating: '9.4',
    sections: ['Book', 'Sci-Fi'],
    overview: 'The complete set of Frank Herbert sci-fi masterpiece exploring politics on Arrakis.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-7',
    name: 'The Hobbit & The Lord of the Rings (Illustrated Collection)',
    category: 'Read',
    type: 'book',
    year: 2023,
    rating: '9.8',
    sections: ['Book', 'High Fantasy'],
    overview: 'J.R.R. Tolkien legendary epic journey through Middle-earth.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-8',
    name: '1984 & Animal Farm by George Orwell (EPUB)',
    category: 'Read',
    type: 'book',
    year: 2022,
    rating: '9.5',
    sections: ['Book', 'Classics'],
    overview: 'Classic dystopian visions of totalitarian control and surveillance.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-9',
    name: 'Solo Leveling (Light Novel & Manhwa Complete Edition)',
    category: 'Read',
    type: 'novel',
    year: 2024,
    rating: '9.2',
    sections: ['Light Novel', 'Action'],
    overview: 'The complete light novel series chronicling the rise of Shadow Monarch Sung Jinwoo.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-10',
    name: 'Overlord Light Novel (Volumes 1-16 Complete)',
    category: 'Read',
    type: 'novel',
    year: 2023,
    rating: '9.1',
    sections: ['Light Novel', 'Fantasy'],
    overview: 'Momonga is transported into his favorite MMORPG world as the powerful skeletal sorcerer Ainz Ooal Gown.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-11',
    name: 'Batman: The Long Halloween & Year One (CBZ Comic)',
    category: 'Read',
    type: 'comic',
    year: 2022,
    rating: '9.3',
    sections: ['Comic', 'Mystery'],
    overview: 'Classic graphic novel collections remastered in high resolution digital format.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'r-12',
    name: 'Watchmen by Alan Moore (Ultimate Graphic Novel)',
    category: 'Read',
    type: 'comic',
    year: 2022,
    rating: '9.7',
    sections: ['Comic', 'Superhero'],
    overview: 'In an alternate 1985 America, costumed superheroes are part of daily society until a conspiracy strikes.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },

  // ==================== LISTEN (MUSIC, SOUNDTRACKS, AUDIOBOOKS, RADIO) ====================
  {
    id: 'l-1',
    name: 'Hans Zimmer: Live in Prague (Lossless FLAC 24-Bit)',
    category: 'Listen',
    type: 'music',
    year: 2024,
    rating: '9.7',
    sections: ['Music', 'Soundtrack'],
    overview: 'High-resolution recordings of Interstellar, Inception, Gladiator, and The Dark Knight.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'FLAC MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-2',
    name: 'Interstellar: Original Motion Picture Soundtrack (Expanded)',
    category: 'Listen',
    type: 'music',
    year: 2023,
    rating: '9.8',
    sections: ['Music', 'Score'],
    overview: 'The complete organ and orchestral masterpiece by Hans Zimmer.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'FLAC MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-3',
    name: 'Lo-Fi Chill & Beats 24/7 Live Stream Relay',
    category: 'Listen',
    type: 'radio',
    year: 2026,
    rating: '9.5',
    sections: ['Music', 'Lo-Fi'],
    overview: 'Continuous relax and study lo-fi hip hop stream relay with lossless audio quality.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    sources: [{ name: 'STREAM RELAY', badge: 'badge-relay' }]
  },
  {
    id: 'l-4',
    name: 'Anime & Gaming Symphony Soundtracks Collection',
    category: 'Listen',
    type: 'music',
    year: 2024,
    rating: '9.4',
    sections: ['Music', 'Orchestral'],
    overview: 'Orchestral arrangements of Studio Ghibli, Attack on Titan, Final Fantasy, and Elden Ring.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-5',
    name: 'Daft Punk: Complete Discography (Remastered FLAC)',
    category: 'Listen',
    type: 'music',
    year: 2024,
    rating: '9.9',
    sections: ['Music', 'Electronic'],
    overview: 'Discovery, Homework, Random Access Memories, and Alive 2007 in ultra fidelity.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'FLAC MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-6',
    name: 'Queen: Greatest Hits I, II & III (Studio Masters)',
    category: 'Listen',
    type: 'music',
    year: 2023,
    rating: '9.8',
    sections: ['Music', 'Rock'],
    overview: 'Bohemian Rhapsody, Don Stop Me Now, Under Pressure in high-resolution audio.',
    audioUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sources: [{ name: 'STREAM HOST', badge: 'badge-stream' }, { name: 'FLAC MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-7',
    name: 'Atomic Habits Audiobook by James Clear',
    category: 'Listen',
    type: 'audiobook',
    year: 2023,
    rating: '9.3',
    sections: ['Audiobook', 'Self-Dev'],
    overview: 'Unabridged narrator edition with high-bitrate voice mastering.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-8',
    name: 'Dune Audiobook Series by Frank Herbert (Full Cast)',
    category: 'Listen',
    type: 'audiobook',
    year: 2024,
    rating: '9.6',
    sections: ['Audiobook', 'Sci-Fi'],
    overview: 'Full cast dramatic narration of the sci-fi epic.',
    sources: [{ name: 'FILE HOST', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'l-9',
    name: '99% Invisible',
    category: 'Listen',
    type: 'podcast',
    year: 2026,
    rating: '9.4',
    sections: ['Podcast', 'Design'],
    overview: 'Stories about the unnoticed architecture and design that shape everyday life.'
  },
  {
    id: 'l-10',
    name: 'Science Vs',
    category: 'Listen',
    type: 'podcast',
    year: 2026,
    rating: '9.2',
    sections: ['Podcast', 'Science'],
    overview: 'A curious, evidence-led look at the ideas people argue about most.'
  },

  // ==================== PLAY ====================
  {
    id: 'p-1',
    name: 'Elden Ring: Shadow of the Erdtree',
    category: 'Play',
    type: 'game',
    year: 2024,
    rating: '9.8',
    sections: ['PC Game', 'Action RPG'],
    overview: 'Guided by Empyrean Miquella, players explore the Land of Shadow.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'DIRECT MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-2',
    name: 'Cyberpunk 2077: Phantom Liberty',
    category: 'Play',
    type: 'game',
    year: 2024,
    rating: '9.4',
    sections: ['PC Game', 'Open World'],
    overview: 'Return to Night City as V in a high-stakes spy thriller adventure.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'DIRECT MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-3',
    name: 'Grand Theft Auto V',
    category: 'Play',
    type: 'game',
    year: 2024,
    rating: '9.5',
    sections: ['PC Game', 'Action'],
    overview: 'Experience the blockbuster in stunning 4K with ray tracing and ultra settings.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-4',
    name: 'Red Dead Redemption 2',
    category: 'Play',
    type: 'game',
    year: 2024,
    rating: '9.9',
    sections: ['PC Game', 'Open World'],
    overview: 'Arthur Morgan and the Van der Linde gang are outlaws on the run across the rugged heartland of America.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-5',
    name: 'Minecraft',
    category: 'Play',
    type: 'game',
    year: 2024,
    rating: '9.7',
    sections: ['PC Game', 'Sandbox'],
    overview: 'Explore infinite worlds and build everything from simple homes to grand castles.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-6',
    name: 'The Legend of Zelda: Tears of the Kingdom',
    category: 'Play',
    type: 'retro',
    year: 2023,
    rating: '9.9',
    sections: ['Console Game', 'Adventure'],
    overview: 'Explore the vast landscapes of Hyrule and the mysterious islands above it.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-7',
    name: 'Super Mario Odyssey',
    category: 'Play',
    type: 'retro',
    year: 2024,
    rating: '9.7',
    sections: ['Console Game', 'Platformer'],
    overview: 'Join Mario on massive, globe-trotting 3D adventures.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-8',
    name: 'Pokémon Emerald',
    category: 'Play',
    type: 'retro',
    year: 2023,
    rating: '9.8',
    sections: ['Handheld Game', 'RPG'],
    overview: 'A classic adventure through the Hoenn region with a team of Pokémon companions.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-9',
    name: 'Retro Classics',
    category: 'Play',
    type: 'retro',
    year: 2024,
    rating: '9.6',
    sections: ['Arcade', 'Retro Games'],
    overview: 'A place in your library for the classic games you already have installed.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-10',
    name: 'Dark Souls III',
    category: 'Play',
    type: 'game',
    year: 2023,
    rating: '9.6',
    sections: ['PC Game', 'Action RPG'],
    overview: 'As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments.',
    sources: [{ name: 'AUTO DOWNLOAD', badge: 'badge-file' }, { name: 'MIRROR', badge: 'badge-mirror' }]
  },
  {
    id: 'p-11',
    name: 'Civilization VI',
    category: 'Play',
    type: 'game',
    year: 2016,
    rating: '8.8',
    sections: ['PC Game', 'Strategy'],
    overview: 'Build an empire, guide a civilization, and compete across centuries of history.'
  },
  {
    id: 'p-12',
    name: 'Into the Breach',
    category: 'Play',
    type: 'game',
    year: 2018,
    rating: '9.1',
    sections: ['PC Game', 'Strategy'],
    overview: 'A tightly designed turn-based strategy game about protecting cities from an alien threat.'
  }
];
});
